### ISSUE TITLE
Saving images for debugging modifies images in cache

### ISSUE THREAD

**Issue by Andriamanitra** [niladricts/BusinessTampereTrafficMonitoring#17]
When there are multiple traffic light events that use the same frame, the debug images have bounding boxes drawn on them multiple times (by `save_image_for_debugging()` method in object detector). It should be easy to fix by making a copy of the cached frame before modifying and saving it.

**Comment by lassijjk** [comment]
I will fix this in another branch. Issue lies within the stream reader so I'll make it return a copy of the wanted frame.
